// Emits store crud methods from model annotations
package generator

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	protogormv1 "github.com/nickheyer/protogorm/gen/protogorm/v1"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// One parsed query parameter
type queryParam struct {
	name string
	typ  string
}

// Tracks rendering state for one store file
type storeGen struct {
	body      strings.Builder
	needTime  bool
	needUUID  bool
}

// Renders store crud methods attached to a Store type
func RenderStore(models []*Model, pkgName string) ([]byte, error) {
	g := &storeGen{}
	for _, m := range models {
		skip := map[string]bool{}
		for _, s := range m.Opts.Skip {
			skip[s] = true
		}
		if !skip["create"] {
			g.emitCreate(m)
		}
		if !skip["get"] {
			g.emitGet(m)
		}
		if !skip["list"] {
			g.emitList(m)
		}
		if !skip["update"] {
			g.emitUpdate(m)
		}
		if !skip["update_fields"] {
			g.emitUpdateFields(m)
		}
		if !skip["delete"] {
			if err := g.emitDelete(m, models); err != nil {
				return nil, err
			}
		}
		if !skip["count"] {
			g.emitCount(m)
		}
		if m.Opts.Upsert {
			g.emitUpsert(m)
		}
		for _, q := range m.Opts.Queries {
			if err := g.emitQuery(m, q); err != nil {
				return nil, err
			}
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by protogorm. DO NOT EDIT.\n\npackage %s\n\nimport (\n\t\"context\"\n\t\"errors\"\n\t\"fmt\"\n", pkgName)
	if g.needTime {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	if g.needUUID {
		b.WriteString("\t\"github.com/google/uuid\"\n")
	}
	for _, pkg := range modelImports(models) {
		fmt.Fprintf(&b, "\t%s %q\n", pkg.Name, pkg.ImportPath)
	}
	b.WriteString("\t\"gorm.io/gorm\"\n\t\"gorm.io/gorm/clause\"\n)\n")
	b.WriteString(g.body.String())

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format store: %w\n%s", err, b.String())
	}
	return formatted, nil
}

// Model packages sorted for a stable import block
func modelImports(models []*Model) []*Package {
	pkgs := ByPackage(models)
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].ImportPath < pkgs[j].ImportPath })
	return pkgs
}

// Qualified go type for one model
func ref(m *Model) string {
	return m.Pkg.Name + "." + m.Name
}

// True when the model uses a generated uuid id
func uuidPK(m *Model) bool {
	return len(m.PKs) == 1 && m.PKs[0].Kind == protoreflect.StringKind && m.PKs[0].Column == "id" && !m.PKs[0].AutoInc
}

// Go parameter list for the primary key
func pkParams(m *Model) []queryParam {
	var out []queryParam
	for _, pk := range m.PKs {
		out = append(out, queryParam{name: paramName(pk.Column), typ: goKind(pk.Kind)})
	}
	return out
}

// Sql predicate matching the primary key
func pkWhere(m *Model) string {
	var parts []string
	for _, pk := range m.PKs {
		parts = append(parts, pk.Column+" = ?")
	}
	return strings.Join(parts, " AND ")
}

func goKind(k protoreflect.Kind) string {
	switch k {
	case protoreflect.StringKind:
		return "string"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.FloatKind:
		return "float32"
	}
	return "string"
}

func sigOf(params []queryParam) string {
	var parts []string
	for _, p := range params {
		parts = append(parts, p.name+" "+p.typ)
	}
	return strings.Join(parts, ", ")
}

func argsOf(params []queryParam) string {
	var parts []string
	for _, p := range params {
		parts = append(parts, p.name)
	}
	return strings.Join(parts, ", ")
}

// Parses annotation params into typed go parameters
func parseParams(m *Model, specs []string) ([]queryParam, error) {
	var out []queryParam
	for _, s := range specs {
		name, typ, ok := strings.Cut(strings.TrimSpace(s), " ")
		if !ok {
			return nil, fmt.Errorf("model %s has bad query param %q", m.Name, s)
		}
		switch typ {
		case "string", "int", "int32", "int64", "uint", "uint32", "uint64", "bool", "float32", "float64", "time.Time":
		default:
			typ = m.Pkg.Name + "." + typ
		}
		out = append(out, queryParam{name: name, typ: typ})
	}
	return out, nil
}

func usesTime(params []queryParam) bool {
	for _, p := range params {
		if p.typ == "time.Time" {
			return true
		}
	}
	return false
}

// Model matching an annotation reference by name
func findModel(models []*Model, name string) (*Model, error) {
	for _, m := range models {
		if m.Name == name {
			return m, nil
		}
	}
	return nil, fmt.Errorf("no model named %s", name)
}

func (g *storeGen) emitCreate(m *Model) {
	b := &g.body
	fmt.Fprintf(b, "\n// Inserts rows into %s\nfunc (s *Store) Create%s(ctx context.Context, rows ...*%s) error {\n", m.Opts.Table, m.Name, ref(m))
	b.WriteString("\tif len(rows) == 0 {\n\t\treturn nil\n\t}\n")
	if uuidPK(m) {
		g.needUUID = true
		fmt.Fprintf(b, "\tfor _, r := range rows {\n\t\tif r.%s == \"\" {\n\t\t\tr.%s = uuid.New().String()\n\t\t}\n\t}\n", m.PKs[0].GoName, m.PKs[0].GoName)
	}
	b.WriteString("\treturn s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error\n}\n")
}

func (g *storeGen) emitGet(m *Model) {
	b := &g.body
	params := pkParams(m)
	fmt.Fprintf(b, "\n// Loads one row from %s\nfunc (s *Store) Get%s(ctx context.Context, %s) (*%s, error) {\n", m.Opts.Table, m.Name, sigOf(params), ref(m))
	fmt.Fprintf(b, "\tvar row %s\n", ref(m))
	fmt.Fprintf(b, "\tif err := s.db.WithContext(ctx).First(&row, %q, %s).Error; err != nil {\n", pkWhere(m), argsOf(params))
	fmt.Fprintf(b, "\t\tif errors.Is(err, gorm.ErrRecordNotFound) {\n\t\t\treturn nil, fmt.Errorf(\"%s not found: %%w\", gorm.ErrRecordNotFound)\n\t\t}\n\t\treturn nil, err\n\t}\n\treturn &row, nil\n}\n", humanName(m.Name))
}

func (g *storeGen) emitList(m *Model) {
	b := &g.body
	fmt.Fprintf(b, "\n// Lists rows from %s\nfunc (s *Store) List%s(ctx context.Context) ([]*%s, error) {\n", m.Opts.Table, plural(m.Name), ref(m))
	fmt.Fprintf(b, "\tvar rows []*%s\n", ref(m))
	q := "s.db.WithContext(ctx)"
	if m.Opts.OrderBy != "" {
		q += fmt.Sprintf(".Order(%q)", m.Opts.OrderBy)
	}
	fmt.Fprintf(b, "\tif err := %s.Find(&rows).Error; err != nil {\n\t\treturn nil, err\n\t}\n\treturn rows, nil\n}\n", q)
}

func (g *storeGen) emitUpdate(m *Model) {
	b := &g.body
	fmt.Fprintf(b, "\n// Saves one row into %s\nfunc (s *Store) Update%s(ctx context.Context, row *%s) error {\n", m.Opts.Table, m.Name, ref(m))
	b.WriteString("\treturn s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error\n}\n")
}

func (g *storeGen) emitUpdateFields(m *Model) {
	b := &g.body
	params := pkParams(m)
	fmt.Fprintf(b, "\n// Patches columns on one %s row\nfunc (s *Store) Update%sFields(ctx context.Context, %s, fields map[string]any) error {\n", m.Opts.Table, m.Name, sigOf(params))
	b.WriteString("\tif len(fields) == 0 {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(b, "\tres := s.db.WithContext(ctx).Model(&%s{}).Where(%q, %s).Updates(fields)\n", ref(m), pkWhere(m), argsOf(params))
	fmt.Fprintf(b, "\tif res.Error != nil {\n\t\treturn res.Error\n\t}\n\tif res.RowsAffected == 0 {\n\t\treturn fmt.Errorf(\"%s not found: %%w\", gorm.ErrRecordNotFound)\n\t}\n\treturn nil\n}\n", humanName(m.Name))
}

func (g *storeGen) emitDelete(m *Model, models []*Model) error {
	b := &g.body
	params := pkParams(m)
	fmt.Fprintf(b, "\n// Deletes one row from %s\nfunc (s *Store) Delete%s(ctx context.Context, %s) error {\n", m.Opts.Table, m.Name, sigOf(params))

	for _, gd := range m.Opts.Guards {
		guard, err := findModel(models, gd.Model)
		if err != nil {
			return fmt.Errorf("model %s guard: %w", m.Name, err)
		}
		fmt.Fprintf(b, "\tvar refs%s int64\n", gd.Model)
		fmt.Fprintf(b, "\tif err := s.db.WithContext(ctx).Model(&%s{}).Where(%q, %s).Count(&refs%s).Error; err != nil {\n\t\treturn err\n\t}\n", ref(guard), gd.Fk+" = ?", params[0].name, gd.Model)
		fmt.Fprintf(b, "\tif refs%s > 0 {\n\t\treturn fmt.Errorf(\"%s still referenced by %%d %s rows\", refs%s)\n\t}\n", gd.Model, humanName(m.Name), humanName(gd.Model), gd.Model)
	}

	if len(m.Opts.Cascades) == 0 {
		fmt.Fprintf(b, "\treturn s.db.WithContext(ctx).Delete(&%s{}, %q, %s).Error\n}\n", ref(m), pkWhere(m), argsOf(params))
		return nil
	}

	needsParent := false
	for _, c := range m.Opts.Cascades {
		if c.Key != "" && c.Key != m.PKs[0].Column {
			needsParent = true
		}
	}
	b.WriteString("\treturn s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {\n")
	if needsParent {
		fmt.Fprintf(b, "\t\tvar parent %s\n", ref(m))
		fmt.Fprintf(b, "\t\tif err := tx.First(&parent, %q, %s).Error; err != nil {\n\t\t\treturn err\n\t\t}\n", pkWhere(m), argsOf(params))
	}
	for _, c := range m.Opts.Cascades {
		child, err := findModel(models, c.Model)
		if err != nil {
			return fmt.Errorf("model %s cascade: %w", m.Name, err)
		}
		val := params[0].name
		if c.Key != "" && c.Key != m.PKs[0].Column {
			f, err := fieldFor(m, c.Key)
			if err != nil {
				return err
			}
			val = "parent." + f
		}
		fmt.Fprintf(b, "\t\tif err := tx.Delete(&%s{}, %q, %s).Error; err != nil {\n\t\t\treturn err\n\t\t}\n", ref(child), c.Fk+" = ?", val)
	}
	fmt.Fprintf(b, "\t\treturn tx.Delete(&%s{}, %q, %s).Error\n\t})\n}\n", ref(m), pkWhere(m), argsOf(params))
	return nil
}

func (g *storeGen) emitCount(m *Model) {
	b := &g.body
	fmt.Fprintf(b, "\n// Counts rows in %s\nfunc (s *Store) Count%s(ctx context.Context) (int64, error) {\n", m.Opts.Table, plural(m.Name))
	fmt.Fprintf(b, "\tvar count int64\n\terr := s.db.WithContext(ctx).Model(&%s{}).Count(&count).Error\n\treturn count, err\n}\n", ref(m))
}

func (g *storeGen) emitUpsert(m *Model) {
	b := &g.body
	var conflict []string
	for _, pk := range m.PKs {
		conflict = append(conflict, fmt.Sprintf("{Name: %q}", pk.Column))
	}
	var updates []string
	for _, f := range m.Fields {
		if f.Skip || f.Relation || f.PK || f.AutoCreate {
			continue
		}
		updates = append(updates, fmt.Sprintf("%q", f.Column))
	}
	fmt.Fprintf(b, "\n// Inserts or refreshes one %s row\nfunc (s *Store) Upsert%s(ctx context.Context, row *%s) error {\n", m.Opts.Table, m.Name, ref(m))
	if uuidPK(m) {
		g.needUUID = true
		fmt.Fprintf(b, "\tif row.%s == \"\" {\n\t\trow.%s = uuid.New().String()\n\t}\n", m.PKs[0].GoName, m.PKs[0].GoName)
	}
	fmt.Fprintf(b, "\treturn s.db.WithContext(ctx).Omit(clause.Associations).Clauses(clause.OnConflict{\n\t\tColumns:   []clause.Column{%s},\n\t\tDoUpdates: clause.AssignmentColumns([]string{%s}),\n\t}).Create(row).Error\n}\n", strings.Join(conflict, ", "), strings.Join(updates, ", "))
}

// Emits one annotated query
func (g *storeGen) emitQuery(m *Model, q *protogormv1.Query) error {
	b := &g.body
	params, err := parseParams(m, q.Params)
	if err != nil {
		return err
	}
	if usesTime(params) {
		g.needTime = true
	}
	order := q.OrderBy
	if order == "" {
		order = m.Opts.OrderBy
	}
	sig := sigOf(params)
	if sig != "" {
		sig = ", " + sig
	}

	switch q.Kind {
	case protogormv1.QueryKind_QUERY_KIND_GET:
		fmt.Fprintf(b, "\n// Loads one row from %s\nfunc (s *Store) %s(ctx context.Context%s) (*%s, error) {\n", m.Opts.Table, q.Name, sig, ref(m))
		fmt.Fprintf(b, "\tvar row %s\n", ref(m))
		chain := "s.db.WithContext(ctx)"
		for _, p := range q.Preload {
			chain += fmt.Sprintf(".Preload(%q)", p)
		}
		fmt.Fprintf(b, "\tif err := %s.%s.First(&row).Error; err != nil {\n", chain, whereCall(q.Where, argsOf(params)))
		if q.NotFoundNil {
			b.WriteString("\t\tif errors.Is(err, gorm.ErrRecordNotFound) {\n\t\t\treturn nil, nil\n\t\t}\n")
		} else {
			fmt.Fprintf(b, "\t\tif errors.Is(err, gorm.ErrRecordNotFound) {\n\t\t\treturn nil, fmt.Errorf(\"%s not found: %%w\", gorm.ErrRecordNotFound)\n\t\t}\n", humanName(m.Name))
		}
		b.WriteString("\t\treturn nil, err\n\t}\n\treturn &row, nil\n}\n")

	case protogormv1.QueryKind_QUERY_KIND_LIST:
		ret := fmt.Sprintf("([]*%s, error)", ref(m))
		extra := ""
		if q.Paginate {
			ret = fmt.Sprintf("([]*%s, int64, error)", ref(m))
			extra = ", offset, limit int"
		} else if q.LimitArg {
			extra = ", limit int"
		}
		fmt.Fprintf(b, "\n// Lists rows from %s\nfunc (s *Store) %s(ctx context.Context%s%s) %s {\n", m.Opts.Table, q.Name, sig, extra, ret)
		fail := "nil, err"
		if q.Paginate {
			fail = "nil, 0, err"
			fmt.Fprintf(b, "\tvar total int64\n\tcounter := s.db.WithContext(ctx).Model(&%s{})\n", ref(m))
			if q.Where != "" {
				fmt.Fprintf(b, "\tcounter = counter.%s\n", whereCall(q.Where, argsOf(params)))
			}
			b.WriteString("\tif err := counter.Count(&total).Error; err != nil {\n\t\treturn nil, 0, err\n\t}\n")
		}
		fmt.Fprintf(b, "\tvar rows []*%s\n", ref(m))
		b.WriteString("\tq := s.db.WithContext(ctx)\n")
		for _, p := range q.Preload {
			fmt.Fprintf(b, "\tq = q.Preload(%q)\n", p)
		}
		if q.Where != "" {
			fmt.Fprintf(b, "\tq = q.%s\n", whereCall(q.Where, argsOf(params)))
		}
		if order != "" {
			fmt.Fprintf(b, "\tq = q.Order(%q)\n", order)
		}
		if q.Paginate {
			b.WriteString("\tq = q.Offset(offset)\n\tif limit > 0 {\n\t\tq = q.Limit(limit)\n\t}\n")
		} else if q.LimitArg {
			b.WriteString("\tif limit > 0 {\n\t\tq = q.Limit(limit)\n\t}\n")
		} else if q.Limit > 0 {
			fmt.Fprintf(b, "\tq = q.Limit(%d)\n", q.Limit)
		}
		fmt.Fprintf(b, "\tif err := q.Find(&rows).Error; err != nil {\n\t\treturn %s\n\t}\n", fail)
		if q.Paginate {
			b.WriteString("\treturn rows, total, nil\n}\n")
		} else {
			b.WriteString("\treturn rows, nil\n}\n")
		}

	case protogormv1.QueryKind_QUERY_KIND_DELETE:
		fmt.Fprintf(b, "\n// Deletes rows from %s\nfunc (s *Store) %s(ctx context.Context%s) error {\n", m.Opts.Table, q.Name, sig)
		fmt.Fprintf(b, "\tres := s.db.WithContext(ctx).%s.Delete(&%s{})\n", whereCall(q.Where, argsOf(params)), ref(m))
		b.WriteString("\tif res.Error != nil {\n\t\treturn res.Error\n\t}\n")
		if q.RequireRow {
			fmt.Fprintf(b, "\tif res.RowsAffected == 0 {\n\t\treturn fmt.Errorf(\"%s not found: %%w\", gorm.ErrRecordNotFound)\n\t}\n", humanName(m.Name))
		}
		b.WriteString("\treturn nil\n}\n")

	case protogormv1.QueryKind_QUERY_KIND_EXISTS:
		fmt.Fprintf(b, "\n// Reports whether a matching %s row exists\nfunc (s *Store) %s(ctx context.Context%s) (bool, error) {\n", m.Opts.Table, q.Name, sig)
		fmt.Fprintf(b, "\tvar count int64\n\terr := s.db.WithContext(ctx).Model(&%s{}).%s.Count(&count).Error\n\treturn count > 0, err\n}\n", ref(m), whereCall(q.Where, argsOf(params)))

	case protogormv1.QueryKind_QUERY_KIND_COUNT:
		fmt.Fprintf(b, "\n// Counts matching rows in %s\nfunc (s *Store) %s(ctx context.Context%s) (int64, error) {\n", m.Opts.Table, q.Name, sig)
		fmt.Fprintf(b, "\tvar count int64\n\terr := s.db.WithContext(ctx).Model(&%s{}).%s.Count(&count).Error\n\treturn count, err\n}\n", ref(m), whereCall(q.Where, argsOf(params)))

	case protogormv1.QueryKind_QUERY_KIND_UPDATE:
		fmt.Fprintf(b, "\n// Patches matching rows in %s\nfunc (s *Store) %s(ctx context.Context%s) error {\n", m.Opts.Table, q.Name, sig)
		stmt := fmt.Sprintf("UPDATE %s SET %s WHERE %s", m.Opts.Table, q.Set, q.Where)
		if len(params) == 0 {
			fmt.Fprintf(b, "\tres := s.db.WithContext(ctx).Exec(%q)\n", stmt)
		} else {
			fmt.Fprintf(b, "\tres := s.db.WithContext(ctx).Exec(%q, %s)\n", stmt, argsOf(params))
		}
		b.WriteString("\tif res.Error != nil {\n\t\treturn res.Error\n\t}\n")
		if q.RequireRow {
			fmt.Fprintf(b, "\tif res.RowsAffected == 0 {\n\t\treturn fmt.Errorf(\"%s not found: %%w\", gorm.ErrRecordNotFound)\n\t}\n", humanName(m.Name))
		}
		b.WriteString("\treturn nil\n}\n")

	default:
		return fmt.Errorf("query %s on %s has no kind", q.Name, m.Name)
	}
	return nil
}

// Go field name for a column on this model
func fieldFor(m *Model, column string) (string, error) {
	for _, f := range m.Fields {
		if f.Column == column {
			return f.GoName, nil
		}
	}
	return "", fmt.Errorf("model %s has no column %s", m.Name, column)
}

// Where invocation with optional bound args
func whereCall(where string, args string) string {
	if args == "" {
		return fmt.Sprintf("Where(%q)", where)
	}
	return fmt.Sprintf("Where(%q, %s)", where, args)
}
