// Emits model support code beside the generated structs
package generator

import (
	"fmt"
	"go/format"
	"strings"
)

// Renders gorm.gen.go for one package of models
func RenderSupport(pkg *Package, models []*Model) ([]byte, error) {
	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by protogorm. DO NOT EDIT.

package %s

import (
	"context"
	"fmt"
	"reflect"
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

func init() {
	schema.RegisterSerializer("tspb", TimestampSerializer{})
}

// Stores protobuf timestamps as database datetime values
type TimestampSerializer struct{}

// Reads a datetime column into a protobuf timestamp
func (TimestampSerializer) Scan(ctx context.Context, field *schema.Field, dst reflect.Value, dbValue any) error {
	if dbValue == nil {
		field.ReflectValueOf(ctx, dst).Set(reflect.Zero(field.FieldType))
		return nil
	}
	var t time.Time
	switch v := dbValue.(type) {
	case time.Time:
		t = v
	case string:
		parsed, err := parseDBTime(v)
		if err != nil {
			return err
		}
		t = parsed
	case []byte:
		parsed, err := parseDBTime(string(v))
		if err != nil {
			return err
		}
		t = parsed
	case int64:
		t = time.Unix(v, 0)
	default:
		return fmt.Errorf("tspb: unsupported db value %%T", dbValue)
	}
	if t.IsZero() {
		field.ReflectValueOf(ctx, dst).Set(reflect.Zero(field.FieldType))
		return nil
	}
	field.ReflectValueOf(ctx, dst).Set(reflect.ValueOf(timestamppb.New(t)))
	return nil
}

// Writes a protobuf timestamp as a database time value
func (TimestampSerializer) Value(ctx context.Context, field *schema.Field, dst reflect.Value, fieldValue any) (any, error) {
	ts, ok := fieldValue.(*timestamppb.Timestamp)
	if !ok || ts == nil {
		return nil, nil
	}
	return ts.AsTime(), nil
}

// Accepts the datetime layouts common drivers emit
func parseDBTime(s string) (time.Time, error) {
	layouts := []string{
		"2006-01-02 15:04:05.999999999-07:00",
		"2006-01-02 15:04:05.999999999",
		time.RFC3339Nano,
		"2006-01-02 15:04:05",
		"2006-01-02T15:04:05.999999999",
	}
	var last error
	for _, layout := range layouts {
		t, err := time.Parse(layout, s)
		if err == nil {
			return t, nil
		}
		last = err
	}
	return time.Time{}, fmt.Errorf("tspb: cannot parse %%q: %%w", s, last)
}

`, pkg.Name)

	for _, m := range models {
		fmt.Fprintf(&b, "func (*%s) TableName() string { return %q }\n\n", m.Name, m.Opts.Table)

		if m.Created != "" {
			fmt.Fprintf(&b, "func (x *%s) BeforeCreate(*gorm.DB) error {\n", m.Name)
			fmt.Fprintf(&b, "\tif x.%s == nil {\n\t\tx.%s = timestamppb.Now()\n\t}\n\treturn nil\n}\n\n", m.Created, m.Created)
		}
		if m.Updated != "" {
			fmt.Fprintf(&b, "func (x *%s) BeforeSave(*gorm.DB) error {\n", m.Name)
			fmt.Fprintf(&b, "\tx.%s = timestamppb.Now()\n\treturn nil\n}\n\n", m.Updated)
		}
		if len(m.Redacts) > 0 {
			fmt.Fprintf(&b, "// Clears secret fields before the message leaves the app\nfunc (x *%s) Redact() *%s {\n\tif x == nil {\n\t\treturn nil\n\t}\n", m.Name, m.Name)
			for _, r := range m.Redacts {
				fmt.Fprintf(&b, "\tx.%s = \"\"\n", r)
			}
			b.WriteString("\treturn x\n}\n\n")
		}
	}

	b.WriteString("// Every table for automigrate\nfunc AllModels() []any {\n\treturn []any{\n")
	for _, m := range models {
		fmt.Fprintf(&b, "\t\t&%s{},\n", m.Name)
	}
	b.WriteString("\t}\n}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format support: %w\n%s", err, b.String())
	}
	return formatted, nil
}
